import { useMemo, useState } from "react";

const inventory = [
  { id:"gsn", name:"GSN Network", type:"Sports media", audience:"Sports", price:350, copy:"Sponsored stories, social placements and network visibility.", tone:"green" },
  { id:"next", name:"GSN Next League", type:"League partnership", audience:"Youth sport", price:900, copy:"Season, matchday and player-development sponsorship opportunities.", tone:"orange" },
  { id:"wave", name:"BrownGlobal Wave", type:"Video & channels", audience:"Entertainment", price:500, copy:"Pre-roll, channel sponsorship and original-programming integrations.", tone:"violet" },
  { id:"kaieteur", name:"Kaieteur House", type:"Publishing", audience:"Readers", price:180, copy:"Book spotlights, reader campaigns and publishing partnerships.", tone:"blue" },
  { id:"network", name:"BrownGlobal Network", type:"Multi-property", audience:"Broad", price:1200, copy:"A coordinated campaign across eligible BrownGlobal properties.", tone:"lime" },
];
const filters = ["All", "Sports", "Youth sport", "Entertainment", "Readers", "Broad"];

export default function App(){
  const [filter,setFilter] = useState("All");
  const [selected,setSelected] = useState<string[]>(["gsn","wave"]);
  const [months,setMonths] = useState(1);
  const shown = filter === "All" ? inventory : inventory.filter(item => item.audience === filter);
  const estimate = useMemo(()=>inventory.filter(item=>selected.includes(item.id)).reduce((sum,item)=>sum+item.price,0)*months,[selected,months]);
  const toggle=(id:string)=>setSelected(current=>current.includes(id)?current.filter(item=>item!==id):[...current,id]);
  const names=inventory.filter(item=>selected.includes(item.id)).map(item=>item.name).join(", ");
  const request=`mailto:admin@brownglobal.app?subject=${encodeURIComponent("BrownGlobal Reach campaign request")}&body=${encodeURIComponent(`Hello BrownGlobal Reach,\n\nPlease prepare a campaign plan for: ${names || "Please help me choose"}.\nPlanning duration: ${months} month${months>1?"s":""}.\nStarting estimate shown: $${estimate.toLocaleString()} USD.\n\nBusiness name:\nCampaign goal:\nPreferred launch date:\n`)}`;
  return <main>
    <header className="topbar"><a className="wordmark" href="#top"><img src="/reach-logo.svg" alt="BrownGlobal Reach logo"/><span>BrownGlobal <b>Reach</b></span></a><nav><a href="#network">Opportunities</a><a href="#process">How it works</a><a href="#standards">Standards</a><a href="#business">Business</a></nav><a className="button dark small" href="#planner">Plan a campaign <span>â†—</span></a></header>
    <section className="hero" id="top"><div className="hero-copy"><span className="eyebrow"><i/>Direct advertising & sponsorships</span><h1>Put your brand in the <em>right moments.</em></h1><p>Plan thoughtful campaigns across sports, streaming, publishing and BrownGlobal-owned experiencesâ€”with a real team reviewing every placement.</p><div className="actions"><a className="button primary" href="#planner">Build a campaign <span>â†’</span></a><a className="text-link" href="mailto:admin@brownglobal.app?subject=BrownGlobal%20Reach%20media%20kit">Request the media kit â†—</a></div></div><div className="campaign-card"><div className="campaign-head"><span>CAMPAIGN 01</span><b>Community in motion.</b><span>PLANNING</span></div><div className="campaign-visual"><div className="rings"><i/><i/><i/></div><strong>REACH<br/>THE<br/>MOMENT.</strong><span>GSN Ã— WAVE</span></div><div className="campaign-foot"><div><small>OBJECTIVE</small><b>Awareness</b></div><div><small>PLACEMENTS</small><b>04</b></div><div><small>REVIEW</small><b>Human-led</b></div></div></div></section>
    <div className="promise"><span>DIRECT PARTNERSHIPS</span><b>â€¢</b><span>BRAND-SAFE REVIEW</span><b>â€¢</b><span>CLEAR REPORTING</span><b>â€¢</b><span>NO BEHAVIORAL TARGETING</span></div>
    <section className="network" id="network"><div className="section-intro"><span className="eyebrow light"><i/>The network</span><h2>Different audiences.<br/>One campaign team.</h2><p>Choose a property or let Reach assemble the right combination around your objective.</p></div><div className="inventory-grid">{inventory.map((item,index)=><article className={item.tone} key={item.id}><span className="number">0{index+1}</span><div className="property-mark">{item.name.split(" ").map(word=>word[0]).join("").slice(0,2)}</div><div><small>{item.type}</small><h3>{item.name}</h3><p>{item.copy}</p></div><footer><span>From ${item.price.toLocaleString()} USD</span><button onClick={()=>{toggle(item.id);document.getElementById("planner")?.scrollIntoView()}}>Add to plan â†’</button></footer></article>)}</div></section>
    <section className="planner" id="planner"><div className="planner-copy"><span className="eyebrow"><i/>Campaign planner</span><h2>Start with the places that fit.</h2><p>Select opportunities to create a planning estimate. Final pricing follows a campaign review, availability check and written proposal.</p><aside><b>BrownGlobal Business member?</b><span>Eligible plans can receive campaign-planning support and selected member benefits.</span></aside></div><div className="planner-card"><div className="planner-head"><div><small>STEP 01</small><h3>Choose your placements</h3></div><span>{selected.length} selected</span></div><div className="filters">{filters.map(item=><button className={filter===item?"active":""} onClick={()=>setFilter(item)} key={item}>{item}</button>)}</div><div className="list">{shown.map(item=><button className={selected.includes(item.id)?"selected":""} onClick={()=>toggle(item.id)} key={item.id}><span className="box">{selected.includes(item.id)?"âœ“":""}</span><span><b>{item.name}</b><small>{item.type}</small></span><strong>${item.price.toLocaleString()}+</strong></button>)}</div><div className="duration"><label htmlFor="months">Planning duration</label><select id="months" value={months} onChange={event=>setMonths(Number(event.target.value))}><option value="1">1 month</option><option value="2">2 months</option><option value="3">3 months</option></select></div><div className="estimate"><span><small>STARTING ESTIMATE</small><b>${estimate.toLocaleString()} <em>USD</em></b></span><a className="button primary" href={request}>Request my plan <span>â†’</span></a></div></div></section>
    <section className="process" id="process"><div className="section-intro centered"><span className="eyebrow light"><i/>How Reach works</span><h2>Clear from brief to report.</h2></div><div className="steps">{[["01","Share the goal","Tell us what the campaign should accomplish, who it is for and when it should run."],["02","Build the plan","Reach confirms eligible properties, formats, pricing, disclosures and availability."],["03","Approve & launch","You approve the written proposal and creative before any campaign begins."],["04","Review results","Receive a straightforward summary of completed placements and available results."]].map(step=><article key={step[0]}><span>{step[0]}</span><h3>{step[1]}</h3><p>{step[2]}</p></article>)}</div></section>
    <section className="standards" id="standards"><div><span className="eyebrow"><i/>Reach standards</span><h2>Trust is part of the placement.</h2></div><div>{[["Clearly identified","Sponsored placements and material relationships should be presented plainly."],["Reviewed by people","Every advertiser and creative concept is checked before acceptance."],["Appropriate for the audience","Youth-focused inventory excludes betting, alcohol, tobacco, adult and misleading offers."],["Privacy-respecting","Reach starts with direct contextual placementsâ€”not behavioral profiles or real-time auctions."]].map(item=><article key={item[0]}><b>{item[0]}</b><p>{item[1]}</p></article>)}</div></section>
    <section className="business" id="business"><div className="business-mark"><img src="/brownglobal-icon.png" alt=""/><small>BROWNGLOBAL<br/>BUSINESS</small></div><div><span className="eyebrow"><i/>Connected to Studio</span><h2>Campaigns are one part of the business.</h2><p>Organize your team, content and BrownGlobal products in Studio. BrownGlobal Business will connect eligible Studio, Flow and Reach benefits while every platform remains available separately.</p></div><a className="button outline" href="mailto:admin@brownglobal.app?subject=BrownGlobal%20Business">Ask about Business <span>â†—</span></a></section>
    <section className="cta"><span className="eyebrow light"><i/>Start a conversation</span><h2>What should your brand reach next?</h2><a className="button primary" href="mailto:admin@brownglobal.app?subject=BrownGlobal%20Reach%20campaign">Plan a campaign <span>â†’</span></a></section>
    <footer className="site-footer"><a className="wordmark" href="#top"><img src="/reach-logo.svg" alt="BrownGlobal Reach logo"/><span>BrownGlobal <b>Reach</b></span></a><p>Direct advertising and sponsorships across the BrownGlobal network.</p><div><a href="mailto:admin@brownglobal.app">admin@brownglobal.app</a><span>Â© 2026 BrownGlobal Holdings LLC</span></div></footer>
  </main>;
}

